name: App Lint

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2
      - name: Up Container
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up -d app
      - name: Run lint and autoflake
        run: make lint
